name: pytorch_learning
channels:
  - pytorch
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py36h2bbff1b_1
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - certifi=2021.5.30=py36haa95532_0
  - cffi=1.14.6=py36h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - dataclasses=0.8=pyh4f3eec9_6
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py36_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - icc_rt=2022.1.0=h6049295_2
  - importlib-metadata=4.8.1=py36haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py36_0
  - jinja2=3.0.3=pyhd3eb1b0_0
  - jpeg=9e=h2bbff1b_1
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.8.1=py36haa95532_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.17.2=h23ce68f_1
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py36h2bbff1b_0
  - mistune=0.8.4=py36he774522_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.3.0=py36h46781fe_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.3.1=py36haa95532_0
  - nbconvert=5.6.1=py36_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.3=py36haa95532_0
  - numpy=1.19.2=py36hadc3359_0
  - numpy-base=1.19.2=py36ha3acd2a_0
  - olefile=0.46=pyhd3eb1b0_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandoc=2.12=haa95532_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py36h8f6046a_0
  - pip=21.2.2=py36haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - protobuf=3.17.2=py36hd77b12b_0
  - py-opencv=3.4.2=py36hc319ecb_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py36he774522_0
  - python=3.6.13=h3758d61_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=228=py36hbaba5e8_1
  - pywinpty=0.5.7=py36_0
  - pyzmq=22.2.1=py36hd77b12b_1
  - scipy=1.5.2=py36h9439919_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py36haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - terminado=0.9.4=py36haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.1=py36h2bbff1b_0
  - traitlets=4.3.3=py36haa95532_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py36_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - cpuonly=2.0=0
  - pytorch=1.10.2=py3.6_cpu_0
  - pytorch-mutex=1.0=cpu
  - torchaudio=0.10.2=py36_cpu
  - torchvision=0.11.3=py36_cpu
prefix: C:\Users\Lau Chinyuan\Anaconda3\envs\pytorch_learning

